### ISSUE TITLE
nb is incompatible with async/await which is now in stable

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/nb#19]
As noticed when trying to change `embedded-hal` to edition 2018, a number of examples using the `nb::await!` macro fail to compile: https://github.com/rust-embedded/embedded-hal/pull/167

However async/await is currently not available in `no_std` due to the implicit use of TLS.

Can we come up with some workaround might would us to unbreak the use of the primitives provided by this crate or should we leave `nb` unchanged and remove the offending examples until async/await becomes usable?

cc @japaric 
cc @Nemo157 
cc @no111u3

**Comment by no111u3** [comment]
I updated review and temporary fixed problems with `nb` but it isn't sounds good - It's looks like a bicycle: r-hash prefixes will ambiguous for library user.

**Comment by no111u3** [comment]
Initial review was merged. Now I have some solution - replace everything of `nb` use to `core::task::Poll`: https://github.com/rust-embedded/embedded-hal/pull/171. But I have no solution to change nb package as crate.

**Comment by therealprof** [comment]
I think we can close this for now. For async/await we'll come up with a different plan an we're going to keep this as is for now.
