### ISSUE TITLE
`package.rust-version` does not match MSRV

### ISSUE THREAD

**Issue by Beanow** [rust-embedded/nb#43]
https://github.com/rust-embedded/nb/pull/42 bumped the MSRV but forgot the Cargo file.
https://github.com/rust-embedded/nb/blob/62c17d3eeda3d53db0fa813e8a0e5b7e84ba6614/Cargo.toml#L14

**Comment by eldruin** [comment]
Nice catch, could you submit a PR updating it?

**Comment by Beanow** [comment]
Sure, made one now
